### ISSUE TITLE
spawnSync /bin/sh ENOBUFS

### ISSUE THREAD

**Issue by nhnkl159** [jellyedwards/gitsweep#6]
Hey, amazing extension. for some reason when I'm installing it when adding a new untracked file it works but when I try to see the list of untracked and reloading, it shows an error message called: "spawnSync /bin/sh ENOBUFS".

using a mac btw, anything I can do?

**Comment by jellyedwards** [comment]
Hi, thanks very much!

It uses `child_process.execSync` which according to https://stackoverflow.com/questions/63796633/spawnsync-bin-sh-enobufs there's a buffer limit (200Kb). Perhaps the output from `git ls-files -v` exceeds the buffer for you. Could you could try piping that command to a file and seeing what size it is please? I managed to reproduce the bug but had to get the output to 1Mb instead (https://nodejs.org/api/child_process.html#child_processspawnsynccommand-args-options might be more accurate).

The SO post also says spawn might work so I'll try build a version with that & maybe you could test it out? (I don't have a mac)

**Comment by jellyedwards** [comment]
Here's an extension package with spawn instead of exec, worked for me! 
[gitsweep-0.0.8.zip](https://github.com/jellyedwards/gitsweep/files/7809648/gitsweep-0.0.8.zip)

You'll have to install it manually with Install from VSIX on the extensions tab:
![image](https://user-images.githubusercontent.com/14051992/148107023-bc74e562-76cb-41ac-9bbe-a419c02e1771.png)

If it works for you I'll check it in & publish - cheers

**Comment by nhnkl159** [comment]
@jellyedwards seems to work! 
thanks!

**Comment by jellyedwards** [comment]
Cool! I'll publish that shortly...
